# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aac8d5e25a30178965dedbb5218c943a9bb98a4e7737b7564fe91179b1795c8a760f7f22d3e57c18654e61ab92b58bac508076ccfde0aa05e2914f67e508f6d9

test:
  secret_key_base: ed78921d468c2fab520c156f5375a5476f5a32ed220eb7022858e2ec67acac992415e39ad89aa5b81db128634b714b04134590c0ff31636dd7a5bcee4ef35b4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
